meta_title: "Higher"
meta_description: "The superior way to hire: Free, Better, & Discrimination-free ATS"
meta_image: "higher-black.png" # Une image dans votre dossier app/assets/images/
#twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
